global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Wasm_DataGrid.Models;
global using Wasm_DataGrid.Presentation;
global using Wasm_DataGrid.DataContracts;
global using Wasm_DataGrid.DataContracts.Serialization;
global using Wasm_DataGrid.Services.Caching;
global using Wasm_DataGrid.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
